### ISSUE TITLE
how to breakpoint my local web server?

### ISSUE THREAD

**Issue by slifin** [bwoebi/phpdbg-docs#1]
Is there a way of setting a breakpoint then when nginx php-fpm executes that file, phpdbg stalls the process and allows me to interact at the breakpoint?

**Comment by krakjoe** [comment]
No.

**Comment by krakjoe** [comment]
phpdbg is primarily a CLI debugger, and is not suitable for debugging an fpm stack.

xdebug is suitable for such things, and I suggest you look to that ...
